image: node:latest

stages:
  - build
  - deploy

variables:
  ANGULAR_ENV: production

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm install
    - ng build --configuration=$ANGULAR_ENV

deploy:
  stage: deploy
  only:
    - master # Deploy only when changes are pushed to the master branch
  script:
    - npm install -g vercel
    - vercel --prod
